### ISSUE TITLE
Wikidata reconciliation sorting order

### ISSUE THREAD

**Issue by rjstapel** [WorldHistoricalGazetteer/whgazetteer#24]
In reconciling wikidata, the results are ordered by their wikidata-identifyer, sorted from high to low. Lower id's are typically older (?), and therefore represent places rather than churches, buildings, etc, so it would be preferable if they would be top of the list rather than bottom.

**Comment by kgeographer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [gh](https://trello.com/c/1oGmav8D/25-gh)

**Comment by kgeographer** [comment]
Wikidata hits for a record are now listed by 'score' (descending). Scores are # of matched elements in complex queries. For example, a hit matching a name variant and type will have a higher score than one matching only a variant.
