### ISSUE TITLE
Conflicting requirements

### ISSUE THREAD

**Issue by tomersagi** [WorldHistoricalGazetteer/whgazetteer#72]
Current requirements file causes the following conflicts:

```
The conflict is caused by:
    The user requested click==8.0.4
    black 22.1.0 depends on click>=8.0.0
    click-default-group 1.2.2 depends on click
    click-didyoumean 0.3.0 depends on click>=7
    click-plugins 1.1.1 depends on click>=4.0
    click-repl 0.2.0 depends on click
    cligj 0.7.2 depends on click>=4.0
    datapackage 1.15.2 depends on click>=6.7
    elastic-wikidata 1.0.1 depends on click==7.1.2
```

**Comment by tomersagi** [comment]
It seems elastic-wikidata is causing the problem. A quick search shows that it is not currently used. Perhaps remove the requirement for this package from the requirements file?

**Comment by kgeographer** [comment]
Sorry for the delay...Just finished creating and testing [a routine for standing up a local instance of WHG](https://github.com/WorldHistoricalGazetteer/whgazetteer/blob/main/docs/cloning/cloning.md), and there is now [a `reqmin.txt` file](https://github.com/WorldHistoricalGazetteer/whgazetteer/blob/main/reqmin.txt) in the project root, which so far _appears to_ enable all functionality.
